version: '3.8'
services:
  postgres:
    container_name: postgresAuction
    image: postgres:13
    networks:
      - backend-local-networks
    environment:
      POSTGRES_PASSWORD: admin123456
      POSTGRES_USER: admin
      POSTGRES_DB: auctiondb
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadminAuction
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
        - 5050:80
    networks:
        - backend-local-networks
    restart: unless-stopped
  adminer:
    container_name: adminerAuction
    image: adminer
    restart: unless-stopped
    ports:
      - 9080:8080
    networks:
      - backend-local-networks
networks:
  backend-local-networks:
volumes:
  pgdata:
